### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by Zhonghexin** [lumaku/ctc-segmentation#25]
Defaulting to user installation because normal site-packages is not writeable
Collecting ctc-segmentation
  Using cached ctc_segmentation-1.7.4.tar.gz (73 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: Cython in c:\users\zhx\appdata\roaming\python\python39\site-packages (from ctc-segmentation) (0.29.32)
Requirement already satisfied: numpy in c:\users\zhx\appdata\roaming\python\python39\site-packages (from ctc-segmentation) (1.23.4)
Requirement already satisfied: setuptools in c:\program files\python39\lib\site-packages (from ctc-segmentation) (56.0.0)
Building wheels for collected packages: ctc-segmentation
  Building wheel for ctc-segmentation (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for ctc-segmentation (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-39
      creating build\lib.win-amd64-cpython-39\ctc_segmentation
      copying ctc_segmentation\ctc_segmentation.py -> build\lib.win-amd64-cpython-39\ctc_segmentation
      copying ctc_segmentation\partitioning.py -> build\lib.win-amd64-cpython-39\ctc_segmentation
      copying ctc_segmentation\__init__.py -> build\lib.win-amd64-cpython-39\ctc_segmentation
      running build_ext
      building 'ctc_segmentation.ctc_segmentation_dyn' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ctc-segmentation
Failed to build ctc-segmentation
ERROR: Could not build wheels for ctc-segmentation, which is required to install pyproject.toml-based projects

**Comment by lumaku** [comment]
The Cython code is compiled at setup. As your error message indicates, `error: Microsoft Visual C++ 14.0 or greater is required`, it seems that you don't have a compiler. Linux distributions usually include build tools such as a compiler, but Windows does not by default. You have to install it for yourself. If you have already a compiler on your system, make sure that the PATH variable is set appropriately.
