### ISSUE TITLE
cann't find 'gratis_blank'

### ISSUE THREAD

**Issue by Alex-Songs** [lumaku/ctc-segmentation#28]
cann't find 'gratis_blank'

**Comment by lumaku** [comment]
`gratis_blank` is a parameter in Espnet or Speechbrain, that is mapped to `blank_transition_cost_zero`, if you can't find it, use the parameter directly

https://github.com/lumaku/ctc-segmentation/blob/69bd9b53b7b82ad926d35e7b280f957ed299a7db/ctc_segmentation/ctc_segmentation.py#L55
