### ISSUE TITLE
What is the difference between <blank> and self-transition?

### ISSUE THREAD

**Issue by houwenxin** [lumaku/ctc-segmentation#9]
Thank you for providing this useful toolkit! I am new to it and is learning it, as I know, <blank> in ctc means the continuing the last character, then what does the self-transition mean? Can I treat them as the same?

**Comment by lumaku** [comment]
Thanks! I hope that this code is useful for you.

CTC was modeled after HMMs, that is why a neural network that was trained with CTC is described with HMM terms. HMMs consist of states, transitions and observation probabilities. To get to know better how CTC works, I really can recommend you to read about HMMs and the introduction to CTC in the dissertation of Alex Graves.

Let's view it from a theoretical perspective and say, that a neural network that was trained with CTC outputs characters in the form of state probabilites. For each character, the network has one output neuron. To make such a method work with neural networks, an additional state has to be added: the "blank" state when no other character occurs.
When training a CTC network, blank states are put in-between characters. For CTC segmentation, this is optional.

So the output of the neural network indicates in which hidden "character" state the sequence is in - at a given time step. If the state does not change within the next time step, that's a self-transition. For CTC, a self-transition ideally happens in a blank state. For the model that CTC segmentation uses, a self-transition can also happen at a certain character.

The `CtcSegmentationParameters()` module has some options that modify the state sequences (e.g., blanks between chars or not) and how the transition probabilities are calculated (self-transition in a blank state is for free etc.). You can adapt these to your needs.

**Comment by houwenxin** [comment]
Great, thank you for the detailed explanation! Maybe I will look into your code for details of the calculation.

**Comment by houwenxin** [comment]
Would it be possible to use this algorithm for Frame-Label alignment? For example, if the result is "<blank> a b <self-transition> <self-transition> c d", can we treat the 2nd frame as the frame duration of "a", "b <self-transition> <self-transition>" as the frame duration of "b" (which is longer)?

**Comment by lumaku** [comment]
You might want to take a look at `state_list`: For each time step, i.e. frame, a current state ("the probable character at this time step") is given in the variable `state_list` which is returned by `ctc_segmentation()`.

**Comment by houwenxin** [comment]
Great, thank you very much! Maybe word-based vocabulary will lead to better alignment, but some papers show that character-based or subword-based vocabulary will help improve the performance to some extent. Is that true?

**Comment by lumaku** [comment]
Experiments indicate that up to some extent, if the ASR performance of the CTC-based network is better, the accuracy of the alignments is higher.

In the description I gave you, I assumed that your CTC-based network uses shorter tokens, such as characters. It depends on many factors (ASR system, dataset, language, ...) whether you get better speech recognition performance with longer/shorter/more/less tokens. It is easier for your ASR system to classify when all of the tokens have a similar probability, so subword units can improve the performance......

**Comment by houwenxin** [comment]
Okay, I think I have learned a lot, thank you very much~
